#include <SDL/SDL.h>
#include <SDL/SDL_image.h>
#include "decoupage.h"
#include "creation_personnages.h"
 ////////////////////////////////////////////////////////////////////////////////
 void creer_joueur_1(personnage *joueur) {
 (*joueur).position.x=30;
 (*joueur).position.y=243+110;
 (*joueur).position.h=40;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_droite=IMG_Load("images/pack_1_right.png");
 (*joueur).sprites_gauche=IMG_Load("images/pack_1_left.png");
 (*joueur).sprites_complementaires=IMG_Load("images/complement_personnage.png");
 (*joueur).sprites_cartouche_droite=IMG_Load("images/cartouche_droite.png");
 (*joueur).sprites_cartouche_gauche=IMG_Load("images/cartouche_gauche.png");
 (*joueur).dernier_deplacement_horizontale=0;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=3;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=16;
 (*joueur).index_sprite_mort=47;
 (*joueur).index_sprite_mort_noyade=57;
 (*joueur).index_sprite_explosion=47;
 (*joueur).FPS_attente=170;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=70;
 (*joueur).FPS_recharge=70;
 (*joueur).FPS_saut=100;
 (*joueur).FPS_mort=200;
 (*joueur).MAX_affichage_cartouches=20;
 (*joueur).contact_avec_le_sol=1;
 (*joueur).collusion_cartouche=1;
 decouper_sprites_gauche((*joueur).ciseau_gauche);
 decouper_sprites_droite((*joueur).ciseau_droite);
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).affichage=1;
 }

/////////////////////////////////////////////////////////////////////////////////
void creer_ennemi_1(personnage *joueur) {
 (*joueur).position.x=659;
 (*joueur).position.y=130+110;
 (*joueur).position.h=40;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_gauche=IMG_Load("images/ennemies_gauche.png");
 (*joueur).sprites_complementaires_2=IMG_Load("images/ennemie_bazouka_gauche.png");///les sprites pour la brulure
 (*joueur).sprites_complementaires=IMG_Load("images/ennemies_gauche.png");
 (*joueur).dernier_deplacement_horizontale=1;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=3;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=16;
 (*joueur).index_sprite_mort=30;
 (*joueur).FPS_attente=250;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=70;
 (*joueur).FPS_mort=200;
 (*joueur).FPS_saut=100;
 (*joueur).MAX_affichage_cartouches=30;
 (*joueur).affichage=1;
 (*joueur).collusion_cartouche=1;
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).contact_avec_le_sol=1;
 (*joueur).hauteur_saut=70;
 decouper_sprites_ennemie_gauche((*joueur).ciseau_gauche);
 decouper_sprites_ennemie_gauche((*joueur).ciseau_droite);
 }
/////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
void creer_ennemi_bazouka(personnage *joueur) {
 (*joueur).position.x=650;
 (*joueur).position.y=127+110;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_droite=IMG_Load("images/ennemie_bazouka_droite.png");
 (*joueur).sprites_gauche=IMG_Load("images/ennemie_bazouka_gauche.png");
 (*joueur).sprites_cartouche_droite=IMG_Load("images/cartouche_bazouka.png");
 (*joueur).sprites_cartouche_gauche=IMG_Load("images/cartouche_bazouka.png");
 (*joueur).dernier_deplacement_horizontale=1;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=6;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=17;
 (*joueur).index_sprite_mort=20;
 (*joueur).FPS_attente=300;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=300;
 (*joueur).FPS_mort=200;
 (*joueur).FPS_saut=100;
 (*joueur).MAX_affichage_cartouches=10;
 (*joueur).affichage=1;
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).contact_avec_le_sol=0;
 (*joueur).hauteur_saut=70;
 decouper_sprites_ennemie_bazouka_gauche((*joueur).ciseau_gauche);
 decouper_sprites_ennemie_bazouka_gauche((*joueur).ciseau_droite);
 }
//////////////////////////////////////////////////////////
void creer_ennemi_arabian(personnage *joueur) {
 (*joueur).position.x=900;
 (*joueur).position.y=227+110;
 (*joueur).position.h=50;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_droite=IMG_Load("images/ennemie_arabian_gauche.png");
 (*joueur).sprites_gauche=IMG_Load("images/ennemie_arabian_gauche.png");
 (*joueur).sprites_cartouche_droite=IMG_Load("images/cartouche_bazouka.png");
 (*joueur).sprites_cartouche_gauche=IMG_Load("images/cartouche_bazouka.png");
 (*joueur).dernier_deplacement_horizontale=1;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=26;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=38;
 (*joueur).index_sprite_mort=6;
 (*joueur).FPS_attente=300;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=300;
 (*joueur).FPS_mort=100;
 (*joueur).FPS_saut=100;
 (*joueur).MAX_affichage_cartouches=10;
 (*joueur).affichage=1;
 (*joueur).collusion_cartouche=1;
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).contact_avec_le_sol=1;
 (*joueur).hauteur_saut=70;
 decouper_sprites_ennemie_arabian_gauche((*joueur).ciseau_gauche);
 decouper_sprites_ennemie_arabian_gauche((*joueur).ciseau_droite);
 }
//////////////////////////////////////////////////////////
void creer_ennemi_sniper(personnage *joueur) {
 (*joueur).position.x=1400;
 (*joueur).position.y=227+110;
 (*joueur).position.h=40;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_gauche=IMG_Load("images/sniper_gauche.png");
 (*joueur).sprites_complementaires=IMG_Load("images/ennemies_gauche.png");
 (*joueur).sprites_cartouche_droite=IMG_Load("images/cartouche_droite.png");
 (*joueur).sprites_cartouche_gauche=IMG_Load("images/cartouche_gauche.png");
 (*joueur).dernier_deplacement_horizontale=1;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=3;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=4;
 (*joueur).index_sprite_mort=15;
 (*joueur).FPS_attente=250;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=200;
 (*joueur).FPS_mort=100;
 (*joueur).FPS_saut=100;
 (*joueur).MAX_affichage_cartouches=30;
 (*joueur).affichage=1;
 (*joueur).collusion_cartouche=1;
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).contact_avec_le_sol=1;
 (*joueur).hauteur_saut=70;
 decouper_sprites_ennemie_sniper((*joueur).ciseau_gauche);
 decouper_sprites_ennemie_sniper((*joueur).ciseau_droite);

 }
 /////////////////////////////////////////////////////////////////////////////////////
 void supprimer_ennemi(personnage *joueur) {
 (*joueur).position.x=0;
 (*joueur).position.y=0;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_droite=NULL;
 (*joueur).sprites_gauche=NULL;
 (*joueur).sprites_complementaires=NULL;
 (*joueur).sprites_cartouche_droite=IMG_Load("images/cartouche_droite.png");
 (*joueur).sprites_cartouche_gauche=IMG_Load("images/cartouche_gauche.png");
 (*joueur).dernier_deplacement_horizontale=1;

 (*joueur).affichage=0;
}
///////////////////////////////////////////////////////////
void creer_ennemi_soldat_blinde(personnage *joueur) {
 (*joueur).position.x=400;
 (*joueur).position.y=227+110;
 (*joueur).position.h=40;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_gauche=IMG_Load("images/soldat_blinde.png");
 (*joueur).sprites_complementaires=IMG_Load("images/ennemies_gauche.png");
 (*joueur).dernier_deplacement_horizontale=1;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=3;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=6;
 (*joueur).index_sprite_mort=15;
 (*joueur).FPS_attente=250;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=250;
 (*joueur).FPS_mort=100;
 (*joueur).FPS_saut=100;
 (*joueur).MAX_affichage_cartouches=30;
 (*joueur).affichage=1;
 (*joueur).collusion_cartouche=1;
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).contact_avec_le_sol=1;
 (*joueur).hauteur_saut=70;
 decouper_sprites_soldat_blinde((*joueur).ciseau_gauche);
 }
 ///////////////////////
 void creer_ennemi_boss(personnage *joueur) {
 (*joueur).position.x=2750;
 (*joueur).position.y=250+110;
 (*joueur).position.h=40;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_gauche=IMG_Load("images/boss.png");
 (*joueur).sprites_cartouche_droite=IMG_Load("images/cartouche_boss2.png");
 (*joueur).sprites_cartouche_gauche=IMG_Load("images/cartouche_boss2.png");
 (*joueur).dernier_deplacement_horizontale=1;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=3;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=5;
 (*joueur).index_sprite_mort=9;
 (*joueur).FPS_attente=300;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=300;
 (*joueur).FPS_mort=500;
 (*joueur).FPS_saut=500;
 (*joueur).MAX_affichage_cartouches=30;
 (*joueur).affichage=1;
 (*joueur).collusion_cartouche=1;
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).contact_avec_le_sol=1;
 (*joueur).hauteur_saut=70;
 decouper_sprites_boss((*joueur).ciseau_gauche);
 }
 /////////////////////////////////////////////////////////////////////////////////
void creer_terminator(personnage *joueur) {
 (*joueur).position.x=2750;
 (*joueur).position.y=200;
 (*joueur).position.h=40;
 (*joueur).ancienne_position=(*joueur).position;
 (*joueur).sprites_gauche=IMG_Load("images/terminator.png");
 (*joueur).sprites_cartouche_gauche=IMG_Load("images/cartouche_boss2.png");
 (*joueur).dernier_deplacement_horizontale=1;
 (*joueur).vitesse_deplacement=1;
 (*joueur).index_sprite_attente=0;
 (*joueur).index_sprite_droite=3;
 (*joueur).index_sprite_gauche=3;
 (*joueur).index_sprite_bas=11;
 (*joueur).index_sprite_saut=35;
 (*joueur).index_sprite_tire=5;
 (*joueur).index_sprite_mort=30;
 (*joueur).FPS_attente=100;
 (*joueur).FPS_deplacement=85;
 (*joueur).FPS_bas=250;
 (*joueur).FPS_tire=500;
 (*joueur).FPS_mort=200;
 (*joueur).FPS_saut=100;
 (*joueur).MAX_affichage_cartouches=30;
 (*joueur).affichage=1;
 (*joueur).collusion_cartouche=1;
 (*joueur).mort=0;
 (*joueur).mort_brulure=0;
 (*joueur).contact_avec_le_sol=1;
 (*joueur).hauteur_saut=70;
 decouper_sprites_terminator((*joueur).ciseau_gauche);
 }

